name: lavoratori_stagionali
description: Progetto di ingegneria del software.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

  intl: ^0.17.0
  bloc: ^8.0.1
  equatable: ^2.0.3
  flow_builder: ^0.0.9

  workers_api:
    path: packages/workers_api
  employees_api:
    path: packages/employees_api
  workers_repository:
    path: packages/workers_repository
  local_storage_workers_api:
    path: packages/local_storage_workers_api
  mongodb_workers_api:
    path: packages/mongodb_workers_api
  authentication_repository:
    path: packages/authentication_repository
  filters:
    path: packages/filters

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274

dev_dependencies:
  test: ^1.16.0
  bloc_test: ^9.0.0
  dependency_validator: ^3.2.0

flutter:
  uses-material-design: true
  generate: true

