name: lavoratori_stagionali
description: Progetto di ingegneria del software.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  intl: ^0.17.0
  workers_api:
    path: packages/workers_api
  workers_repository:
    path: packages/workers_repository
  storage_workers_api:
    path: packages/storage_workers_api


dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

