name: mongodb_workers_api
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  rxdart: ^0.27.2
  mongo_dart: ^0.7.4+1
  workers_api:
    path: ../workers_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
